using System;
using System.Collections.Generic;
using Soulvail.Core.Ports;
using UnityEngine;
using UnityEngine.EventSystems;

namespace Soulvail.Game.Adapters;

/// <summary>
/// A thumb on the arena becomes a place on the ground becomes a command. The body's half of CC
/// §3.4: it knows about screens, cameras and UI, and core knows which enemy is standing there.
/// See AR §3 and §4.1.
/// </summary>
/// <remarks>
/// <para>
/// <b>It decides nothing about targeting.</b> Every judgement here is about input — was this a
/// press, was it on the game or on a button, where on the ground does that pixel correspond to —
/// and the answer is handed over as a world point. Which enemy that means, whether one is close
/// enough, and what happens to the current focus are all <c>FocusResolver</c>'s and
/// <c>Targeter</c>'s (AR §3). An adapter that resolved the enemy itself would be an adapter making
/// a gameplay decision, and the 3 m radius would end up living in the body.
/// </para>
/// <para>
/// <b>Not an <c>ITickable</c>.</b> A command has to land before the snapshot it should influence is
/// built, and registration order is not something to hang that on — VContainer would run this
/// whenever it happened to be registered. <c>RunTicker</c> therefore calls <see cref="Poll"/> from
/// a command phase it runs first, so the whole frame order is one list in one file. M1-16's
/// movement-skill press joins the same phase.
/// </para>
/// <para>
/// Plain C#, not a <see cref="MonoBehaviour"/>: it has no frame of its own, no transform, and
/// nothing in a scene should be able to find it. <c>RunScope</c> builds it and disposes it with the
/// run.
/// </para>
/// </remarks>
public sealed class TapToFocusAdapter
{
    /// <summary>
    /// How near to parallel the camera ray may get to the ground before the intersection is
    /// refused, as the absolute value of the ray direction's Y.
    /// </summary>
    /// <remarks>
    /// Unreachable with <c>FollowCamera</c>'s fixed 57° pitch, where the ray points steeply down
    /// everywhere on screen. It is here because the alternative to refusing is a hit point
    /// kilometres away on the horizon, and a focus command carrying one would be resolved against
    /// an arena it is nowhere near — silently, and only for taps near the top edge.
    /// </remarks>
    private const float MinGroundIncidence = 1e-4f;

    private readonly InputAdapter _input;
    private readonly IPlayerCommands _commands;
    private readonly Camera _camera;

    /// <summary>
    /// The arena floor: the world plane <c>y = 0</c>, which is where every position core reasons
    /// about lives.
    /// </summary>
    /// <remarks>
    /// An instance field rather than a static readonly, so there is no static state in this project
    /// to reason about at all — a <see cref="Plane"/> is 16 bytes and this object is built once per
    /// run.
    /// </remarks>
    private readonly Plane _ground = new Plane(Vector3.up, 0f);

    /// <summary>
    /// Reused by the UI hit test. Allocated once, so a tap costs nothing on the heap after the
    /// first — <see cref="EventSystem.RaycastAll"/> clears and refills the list it is given.
    /// </summary>
    private readonly List<RaycastResult> _uiHits = new List<RaycastResult>(8);

    /// <summary>
    /// Reused likewise. <see cref="PointerEventData"/> is a class, and a new one per tap would be
    /// garbage generated by the most common gesture in the game.
    /// </summary>
    private PointerEventData _pointerData;

    /// <param name="input">The run's input adapter — the only reader of the Input System.</param>
    /// <param name="commands">The run, as the command port. Not <c>IRunSession</c>: this has no business starting or ending one.</param>
    /// <param name="camera">
    /// The camera the arena is seen through, for unprojecting a tap. Assigned from the scene by
    /// <c>RunScope</c> rather than found: <c>Camera.main</c> is a tagged lookup, which is
    /// <c>FindObjectOfType</c> wearing a hat.
    /// </param>
    /// <exception cref="ArgumentNullException">Any dependency is null.</exception>
    public TapToFocusAdapter(InputAdapter input, IPlayerCommands commands, Camera camera)
    {
        _input = input ?? throw new ArgumentNullException(nameof(input));
        _commands = commands ?? throw new ArgumentNullException(nameof(commands));

        // Unity's == rather than `is null`: RunScope supplies this from a serialized field, so an
        // unassigned or destroyed camera is a live reference that only compares equal to null
        // through the engine's operator.
        _camera = camera == null ? throw new ArgumentNullException(nameof(camera)) : camera;
    }

    /// <summary>
    /// Reads this frame's tap, if there was one, and turns it into a focus command.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Four ways to do nothing and one to act, in the order that costs least: no press at all is
    /// almost every frame and returns immediately; a press over UI is ignored entirely rather than
    /// clearing the focus, because a thumb on the stick or on a skill button was never talking to
    /// the arena; and a ray that misses the ground plane is refused rather than guessed at. What is
    /// left is a point on the floor, and even a tap on bare ground is worth sending — that is how
    /// CC §3.4 says the player takes the focus off again.
    /// </para>
    /// <para>
    /// Allocates nothing after the first call: both buffers the UI test needs are fields, and the
    /// world point is a struct.
    /// </para>
    /// </remarks>
    public void Poll()
    {
        if (!_input.FocusPressedThisFrame)
        {
            return;
        }

        Vector2 screenPoint = _input.PointerPosition;

        if (IsOverUi(screenPoint))
        {
            return;
        }

        if (!TryGroundPoint(screenPoint, out Vector3 worldPoint))
        {
            return;
        }

        _commands.FocusTarget(worldPoint.ToNum());
    }

    /// <summary>
    /// Whether a UI raycast target sits under <paramref name="screenPoint"/> — the floating stick's
    /// region, a skill button, or anything else on the canvas.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The M1-09 spec names <c>EventSystem.IsPointerOverGameObject(pointerId)</c>, and this asks
    /// the same question a more reliable way. That overload answers for a pointer the UI module is
    /// already tracking, keyed by an id that is <c>kMouseLeftId</c> for a mouse and the
    /// <em>touch id</em> for a finger — so the id has to be guessed differently per device, and the
    /// wrong guess fails open: it returns false, the tap goes through, and dragging the stick
    /// re-focuses whatever is underneath it. Raycasting the position we already hold has no id in
    /// it to get wrong, and answers identically in the Editor and on a phone.
    /// </para>
    /// <para>
    /// No <see cref="EventSystem"/> in the scene means no UI to be over. That is the truth for a
    /// test scene and for any arena opened without the HUD, and it is the safe direction: the
    /// alternative would be refusing every tap in a scene that has no buttons to protect.
    /// </para>
    /// </remarks>
    private bool IsOverUi(Vector2 screenPoint)
    {
        EventSystem events = EventSystem.current;

        if (events == null)
        {
            return false;
        }

        // Built lazily and kept, because the constructor needs the EventSystem and this object is
        // built before the scene's Awake calls have all run.
        _pointerData ??= new PointerEventData(events);

        _pointerData.Reset();
        _pointerData.position = screenPoint;

        events.RaycastAll(_pointerData, _uiHits);

        return _uiHits.Count > 0;
    }

    /// <summary>
    /// Unprojects <paramref name="screenPoint"/> onto the arena floor.
    /// </summary>
    /// <returns>
    /// <see langword="false"/> when the ray runs too near parallel to the ground or meets it behind
    /// the camera — neither can happen at <c>FollowCamera</c>'s pitch, and both would otherwise
    /// hand core a point from nowhere.
    /// </returns>
    private bool TryGroundPoint(Vector2 screenPoint, out Vector3 worldPoint)
    {
        worldPoint = Vector3.zero;

        Ray ray = _camera.ScreenPointToRay(screenPoint);

        // Negated positives throughout, for the reason MovementSpec documents: every comparison
        // against NaN is false, so the natural spelling would let a NaN pointer position through as
        // a valid hit and put a NaN into core's focus resolution.
        if (!(Mathf.Abs(ray.direction.y) > MinGroundIncidence))
        {
            return false;
        }

        if (!_ground.Raycast(ray, out float distance) || !(distance > 0f))
        {
            return false;
        }

        worldPoint = ray.GetPoint(distance);
        return true;
    }
}
